# Generated by Django 3.1.2 on 2020-10-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('composer', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=100)),
                ('instrument', models.CharField(max_length=100)),
                ('voice', models.CharField(max_length=100)),
                ('own', models.CharField(max_length=100)),
            ],
        ),
    ]
